 syntax="proto3";
 package
// metamodel_version: 1.11.0
// version: 14.1.0
// An agreement having a balance.
message Account
 {
  string name = 0
  string description = 0
 }
// A reference to a place (real or virtual) that can be located by some routing algorithm and where messages or things can be sent or received.
message Address
 {
  string name = 0
  string description = 0
 }
// A category indicating the context or manner in which an address may be used.
message AddressUsageType
 {
  string name = 0
  string description = 0
 }
// A mutually understood arrangement in which two or more parties make commitments to one another.
message Agreement
 {
  string name = 0
  string description = 0
 }
// A measurable characteristic.
message Aspect
 {
  string name = 0
  string description = 0
 }
// A temporal relationship between an assignee, the thing assigned, and the resource that made the assignment.
message Assignment
 {
  string name = 0
  string description = 0
 }
// A category indicating the nature of an activity.
message Behavior
 {
  string name = 0
  string description = 0
 }
// A relatively permanent man-made structure situated on a plot of land, having a roof and walls, commonly used for dwelling, entertaining, or working.
message Building
 {
  string name = 0
  string description = 0
 }
// Any combination of descriptions of things offered together.
message BundledCatalogItem
 {
  string name = 0
  string description = 0
 }
// A description of a product or service to be delivered, given in a sufficient level of detail that a receiver could determine whether delivery constituted discharge of the obligation to deliver.
message CatalogItem
 {
  string name = 0
  string description = 0
 }
// A concept or label used to categorize other instances without specifying any formal semantics.
message Category
 {
  string name = 0
  string description = 0
 }
// A grouping of things.
message Collection
 {
  string name = 0
  string description = 0
 }
// A promise made by a single party to one or more parties to do or not do something or act in a particular way.
message Commitment
 {
  string name = 0
  string description = 0
 }
// Something that, while having an independent existence, is inherently part of or designed to be part of a larger entity, such as a system or network.
message Component
 {
  string name = 0
  string description = 0
 }
// Something which is made up of various parts or elements that are independently identifiable.
message Composite
 {
  string name = 0
  string description = 0
 }
// An event that has started but has not yet ended.
message ContemporaryEvent
 {
  string name = 0
  string description = 0
 }
// Information available in some medium.
message Content
 {
  string name = 0
  string description = 0
 }
// Content reduced to text, audio, etc.
message ContentExpression
 {
  string name = 0
  string description = 0
 }
// An event with a probability of happening in the future, and usually dependent upon some other event or condition.
message ContingentEvent
 {
  string name = 0
  string description = 0
 }
// An obligation that is not yet firm. There is some contingent event whose occurrence will cause the obligation to become firm.
message ContingentObligation
 {
  string name = 0
  string description = 0
 }
// An agreement which can be enforced by law.
message Contract
 {
  string name = 0
  string description = 0
 }
// A specification of some aspect of a contract.
message ContractTerm
 {
  string name = 0
  string description = 0
 }
// A collection of terms approved and managed by some organization or person.
message ControlledVocabulary
 {
  string name = 0
  string description = 0
 }
// A geographic region governed by exactly one country government.
message CountryGeoRegion
 {
  string name = 0
  string description = 0
 }
// A government organization which asserts both sovereignty (i.e., it is not governed by some other government organization) and governance over an entity generally recognized as a country.
message CountryGovernment
 {
  string name = 0
  string description = 0
 }
// The difficulty of reversing a commitment.
message DegreeOfCommitment
 {
  string name = 0
  string description = 0
 }
// An event whose purpose is to establish a specific result, value, or outcome, usually by research, measuring, evaluating, or calculating.
message Determination
 {
  string name = 0
  string description = 0
 }
// An area of study or practice.
message Discipline
 {
  string name = 0
  string description = 0
 }
// An address referring to a locatable virtual place that does not physically exist but is made by software or electronics to appear to do so.
message ElectronicAddress
 {
  string name = 0
  string description = 0
 }
// A category indicating a kind of electronic address. Such a category is usually based on the technology that enables routing to the address referent.
message ElectronicAddressType
 {
  string name = 0
  string description = 0
 }
// Human-made, tangible property other than land or buildings used to perform a task or activity.
message Equipment
 {
  string name = 0
  string description = 0
 }
// A category of equipment.
message EquipmentType
 {
  string name = 0
  string description = 0
 }
// Something that occurs over a period of time, often characterized as an activity being carried out by some person, organization, or software application or brought about by natural forces.
message Event
 {
  string name = 0
  string description = 0
 }
// A characterization of an event that might happen.
message EventSpecification
 {
  string name = 0
  string description = 0
 }
// Content encoded in a specific format, but existing as data independent of any particular physical medium.
message FormattedContent
 {
  string name = 0
  string description = 0
 }
// The activity that a human-made item is intended to perform.
message Function
 {
  string name = 0
  string description = 0
 }
// The real-world media type for content.
message GeneralMediaType
 {
  string name = 0
  string description = 0
 }
// A physical location, with the earth as a frame of reference.
message GeoLocation
 {
  string name = 0
  string description = 0
 }
// An individual point on or above the Earth's surface, identified by latitude, longitude and altitude. Altitude is the distance measured from sea level. If altitude is missing, the point is assumed to be at the Earth's surface. These points are described using decimal latitude/longitude.
message GeoPoint
 {
  string name = 0
  string description = 0
 }
// A bounded region (or set of regions) on the surface of the Earth.
message GeoRegion
 {
  string name = 0
  string description = 0
 }
// An ordered set of geographic points that defines a path from a starting point to an ending point.
message GeoRoute
 {
  string name = 0
  string description = 0
 }
// A three-dimensional space on or near the surface of the Earth.
message GeoVolume
 {
  string name = 0
  string description = 0
 }
// A geographic region governed by at least one government organization.
message GovernedGeoRegion
 {
  string name = 0
  string description = 0
 }
// An independent organization exercising political and/or regulatory authority over a political unit, people, geographical region, etc., as well as performing certain functions for this unit or body.
message GovernmentOrganization
 {
  string name = 0
  string description = 0
 }
// An event which occurred in time, with an actual end earlier than the present moment.
message HistoricalEvent
 {
  string name = 0
  string description = 0
 }
// Content that is used to uniquely identify something or someone.
message ID
 {
  string name = 0
  string description = 0
 }
// An intangible work, invention, or concept, independent of its being expressed in text, audio, video, image, or live performance. IP can also be tacit knowledge, know-how, or skill.
message IntellectualProperty
 {
  string name = 0
  string description = 0
 }
// A goal, desire, or aspiration.
message Intention
 {
  string name = 0
  string description = 0
 }
// An organization whose members are government organizations. This can comprise regional, municipal, state/province, or national level entities.
message IntergovernmentalOrganization
 {
  string name = 0
  string description = 0
 }
// An abstract concept that arises from the distillation of experience. It is similar to a category but, rather than being a simple tag, it has rich structure.
message KnowledgeConcept
 {
  string name = 0
  string description = 0
 }
// Something permanently attached to the Earth.
message Landmark
 {
  string name = 0
  string description = 0
 }
// A recognized, organized set of symbols and grammar.
message Language
 {
  string name = 0
  string description = 0
 }
// Something that is currently, or at some point in time was, alive.
message LivingThing
 {
  string name = 0
  string description = 0
 }
// The amount of a measurable characteristic (aspect).
message Magnitude
 {
  string name = 0
  string description = 0
 }
// A digitized type that computer applications can recognize.
message MediaType
 {
  string name = 0
  string description = 0
 }
// A physical material on which a work can be rendered, represented, or implemented.
message Medium
 {
  string name = 0
  string description = 0
 }
// A specific instance of content sent from a sender to at least one other recipient.
message Message
 {
  string name = 0
  string description = 0
 }
// A composite consisting of nodes connected by links.
message Network
 {
  string name = 0
  string description = 0
 }
// An abstract representation of the connection between two or more nodes in a network.
message NetworkLink
 {
  string name = 0
  string description = 0
 }
// A node in a network.
message NetworkNode
 {
  string name = 0
  string description = 0
 }
// A contingent commitment to buy, sell, swap or provide one or more described or identified goods or services in exchange for another (or others).
message Offer
 {
  string name = 0
  string description = 0
 }
// A collection whose members are ordered in some way.
message OrderedCollection
 {
  string name = 0
  string description = 0
 }
// A member of an ordered collection serving as a proxy for a real world item, which can appear in different orders in different collections. The ordered member appears in exactly one ordered collection.
message OrderedMember
 {
  string name = 0
  string description = 0
 }
// A structured entity formed to achieve specific goals, typically involving members with defined roles.
message Organization
 {
  string name = 0
  string description = 0
 }
// A description of things one is permitted to do.
message Permission
 {
  string name = 0
  string description = 0
 }
// A human being who was or is alive.
message Person
 {
  string name = 0
  string description = 0
 }
// A category indicating the type of an action based on its effect in the physical world.
message PhysicalActionType
 {
  string name = 0
  string description = 0
 }
// An address that refers to a locatable place within the physical universe.
message PhysicalAddress
 {
  string name = 0
  string description = 0
 }
// A category indicating local customary characterizations of physical addresses.
message PhysicalAddressType
 {
  string name = 0
  string description = 0
 }
// An event that can be said to have occurred at some place in space.
message PhysicalEvent
 {
  string name = 0
  string description = 0
 }
// A discrete physical object which, if subdivided, will result in parts that are distinguishable in nature from the whole and in general also from the other parts.
message PhysicalIdentifiableItem
 {
  string name = 0
  string description = 0
 }
// An undifferentiated amount of physical material which, when subdivided, results in each part being indistinguishable in nature from the whole and from every other part.
message PhysicalSubstance
 {
  string name = 0
  string description = 0
 }
// Any of many ways of categorizing products.
message ProductCategory
 {
  string name = 0
  string description = 0
 }
// A description of something that could be physically warehoused or digitally stored and physically or digitally delivered.
message ProductSpecification
 {
  string name = 0
  string description = 0
 }
// A task, usually of longer duration, made up of other tasks.
message Project
 {
  string name = 0
  string description = 0
 }
// A magnitude that was neither measured nor estimated but set by fiat.
message ReferenceValue
 {
  string name = 0
  string description = 0
 }
// Content expressed via some physical medium.
message RenderedContent
 {
  string name = 0
  string description = 0
 }
// The obligation of a person or organization to behave in a certain way.
message Requirement
 {
  string name = 0
  string description = 0
 }
// A description of things one is prevented from doing.
message Restriction
 {
  string name = 0
  string description = 0
 }
// An event with a planned start datetime.
message ScheduledEvent
 {
  string name = 0
  string description = 0
 }
// A task with a planned start datetime.
message ScheduledTask
 {
  string name = 0
  string description = 0
 }
// Superclass for all types of metadata.
message SchemaMetaData
 {
  string name = 0
  string description = 0
 }
// A description of something that can be done for a person or organization (which produces some form of an act).
message ServiceSpecification
 {
  string name = 0
  string description = 0
 }
// The set of characteristics and constraints on their values that specify what it means to be a particular type of thing, such as a material, product, service or event. A specification is sufficiently precise to allow evaluating conformance to the specification.
message Specification
 {
  string name = 0
  string description = 0
 }
// The government of a governed geographic region other than a country which is under the direct or indirect control of a country government.
message SubCountryGovernment
 {
  string name = 0
  string description = 0
 }
// A composite made up of interacting or interdependent components that together operate as a whole.
message System
 {
  string name = 0
  string description = 0
 }
// A term in a folksonomy used to categorize things. Tags can be made up on the fly by users.
message Tag
 {
  string name = 0
  string description = 0
 }
// An activity or piece of work that is either proposed, planned, scheduled, underway, or completed.
message Task
 {
  string name = 0
  string description = 0
 }
// An outline of a task of a particular type, which is the basis for executing such tasks.
message TaskTemplate
 {
  string name = 0
  string description = 0
 }
// Something used to make objects in its own image.
message Template
 {
  string name = 0
  string description = 0
 }
// A relationship existing for a period of time.
message TemporalRelation
 {
  string name = 0
  string description = 0
 }
// Content expressed as a written sequence of characters.
message Text
 {
  string name = 0
  string description = 0
 }
// A span of time with a known start time, end time, and duration. As long as two of the three are known, the third can be inferred.
message TimeInterval
 {
  string name = 0
  string description = 0
 }
// An exchange or transfer of goods, services, or funds.
message Transaction
 {
  string name = 0
  string description = 0
 }
// A collection of units of measure that can all be used to measure the same aspects.
message UnitGroup
 {
  string name = 0
  string description = 0
 }
// A standard amount used to measure or specify things.
message UnitOfMeasure
 {
  string name = 0
  string description = 0
 }
